/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: Natural History Museum Vienna (https://sketchfab.com/NHMWien)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/franz-viehbocks-sokol-space-suit-a2d679620a254660b12c7274de9bfc07
Title: Franz Viehböck's Sokol Space Suit
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[177.484, 282.931, -437.983]}
        rotation={[2.893, 0.395, 0.475]}
        scale={0.001}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material_0}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
